### ISSUE TITLE
Huge FPS drops and stuttering when addonskins is enabled in Wrath - Check video inside.

### ISSUE THREAD

**Issue by wazerstar** [Azilroka/AddOnSkins#171]
I made this video to show you how much performance hit you get by using addonskins.

I could not figure out what addon causing this for months, I would never think of such addon could cause so huge lag spikes when simply hovering mouse over items or moving fast over tooltips..

Video proof.
https://streamable.com/nml7q4

Is this something we can get fixed?

**Comment by Azilroka** [comment]
What skins are enabled?

**Comment by wazerstar** [comment]
> What skins are enabled?

Ok so you put me on quiet a big task here.

I started by testing each row downwards where I ticked an entire road from beginning, and of course its always in the last, aint it always :)?

So I found in the 2nd last row and started halfing until I found the culprit, its Libraries causing it.

So I wonder why does it list ALL those addons I dont have?

And why would we skin Libraries anyways?

I have since then tested with a couple of friends since we are using more or less the same addons and they also complained about stuttering and fps issues, turning Libraries off worked.

More important, why are all those ticked by default?

https://i.imgur.com/IYkPNnZ.png

**Comment by Azilroka** [comment]
Libraries are things like the extra tooltips on some addons.. LibExtraTip, LibQTip, LibDBIcon (Tooltip).. Most likely in your case is the LibExtraTip which is more than likely hooked directly to the GameTooltip which Bagnon has hooked and the other addon that hooked GameTooltip is causing the issue. Which AddOnSkins will exacerbate due to hooking LibExtraTip.
